name: Deploy Python App to Azure Web App (Publish Profile)

on:
  push:
    branches: [ main ]  # Change if using another branch
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: DocuMindSpeak    # Replace with your Azure Web App name
  PYTHON_VERSION: '3.11'                # Change Python version as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # (Optional) Run tests if you have them
      - name: Run tests
        run: |
          if [ -f manage.py ]; then python manage.py test; fi

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./